name: Go Build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/anydone

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - run: go version

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git config --global url."https://_:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Install dependencies
        run: make configure

      - name: Build
        run: make build

